### ISSUE TITLE
Error in installation (incompatible versions of Python and numpy)

### ISSUE THREAD

**Issue by savvas-paragkamian** [GeomScale/dingo#77]
We tried to install dingo on MacBook Pro with M1 Max processor, running macOS Ventura 13.5. 

Python version 3.11.4

We followed the installation steps adapted for the Mac.

```
brew install suite-sparse
```

poetry installation was successful.
```
curl -sSL https://install.python-poetry.org | python3 -
```

The errors were from the step `poetry install  `. 

[dingo_error_m1_mac.txt](https://github.com/GeomScale/dingo/files/12580041/dingo_error_m1_mac.txt)

**Comment by savvas-paragkamian** [comment]
When we tried to use the non-poetry way to install it, we got the following error: 

```
clang: error: unsupported option '-fopenmp'

```

We are not sure this is an M1-relates issue or a general issue for macOS. 

After some digging on the web, we found the following links:

https://mac.r-project.org/openmp/
and
https://www.positioniseverything.net/clang-error-unsupported-option-fopenmp/

that you may find useful.

**Comment by vissarion** [comment]
@savvas-paragkamian thanks for open this issue!

For the poetry approach it seems there is a problem with numpy. Do you have it installed in your system?

For the non poetry approach what is the version of clang you are using? Did you try to upgrade to a newer version? Did you try with gcc?

**Comment by EliseoMolina** [comment]
I had a similar error on Windows using Ubuntu 22 subsystem.

[dingo_installation_error.txt](https://github.com/GeomScale/dingo/files/12585846/dingo_installation_error.txt)

**Comment by vissarion** [comment]
@EliseoMolina 
It is probably something related to incompatible versions of numpy and python. What are the versions of numpy and python you are using locally? 

As a workaround, what happens if you follow the commands from dingo's [github actions workflow](https://github.com/GeomScale/dingo/actions/runs/6035915236/workflow)?

**Comment by hariszaf** [comment]
@vissarion 
Could it be a `CFLAGS` or other -flags type issue?

**Comment by vissarion** [comment]
@hariszaf I am not sure. Do you have some specific flag in mind?

**Comment by hariszaf** [comment]
@savvas-paragkamian @EliseoMolina 
could you please share what you get when you type: 
`echo $CFLAGS`
and 
`echo $LDFLAGS`

**Comment by savvas-paragkamian** [comment]
### Flags

The `$CFLAGS` are empty. 
```
(dingo_p310) talos at programming_projects/dingo % echo $CFLAGS

(dingo_p310) talos at programming_projects/dingo % echo $LDFLAGS
-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++
```

In addition the $LDFLAGS only appear in the poetry environment. This is because of executing the command yesterday during troubleshoting.

Outside the environment there is no $LDFLAGS
```
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++"
```

```
talos at ~ % echo $CFLAGS    

```

### python and lumpy
in the system 
* Python 3.11.4
* numpy 1.23.5

in the conda environments
* Python 3.10.13
* Python 3.11.4
* numpy 1.23.5

in the 2 poetry environments
* numpy 1.23.5
* Python 3.11.4

* Python 3.10.13
* numpy 1.25.2

**Comment by EliseoMolina** [comment]
> @savvas-paragkamian @EliseoMolina could you please share what you get when you type: `echo $CFLAGS` and `echo $LDFLAGS`

The flags are empty: 

em@LAPTOP-2R656OEU:~$ echo $CFLAGS

em@LAPTOP-2R656OEU:~$ echo $LDFLAGS

Python version:  3.11.4

Numpy version:  1.23.5

**Comment by hariszaf** [comment]
@vissarion Eliseo's issue has been fixed.
We still have to figure out Savvas;

**Comment by vissarion** [comment]
@hariszaf thanks, could you please post the solution here for future reference?

**Comment by hariszaf** [comment]
It seems that Python 3.11 has conflicts with the numpy version we use (`1.20.1`)
I switched to that and I made sure that the `git submodule init` command was ran and `dingo` was installed smoothly.

**Comment by vissarion** [comment]
Thanks! @savvas-paragkamian does that solution works for you too?

**Comment by savvas-paragkamian** [comment]
The installation is ok! 

Then I ran the [unit tests](https://github.com/GeomScale/dingo#unit-tests) and got some warnings and errors:

```
(dingo_p310) talos at programming_projects/dingo % python3 tests/fba.py
.This model seems to have metCharge instead of metCharges field. Will use metCharge for what metCharges represents.
Restricted license - for non-production use only - expires 2024-10-28
No defined compartments in model e_coli_core. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e
/Users/talos/miniconda3/envs/dingo_p310/lib/python3.10/site-packages/optlang/gurobi_interface.py:728: DeprecationWarning: Deprecated, pass a TempConstr or use Model.addLConstr
  self.problem.addConstr(lhs, sense, rhs, name=constraint.name)
This model seems to have metCharge instead of metCharges field. Will use metCharge for what metCharges represents.
No defined compartments in model e_coli_core. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e
..
----------------------------------------------------------------------
Ran 3 tests in 0.298s

OK
```

```
(dingo_p310) talos at programming_projects/dingo % python3 tests/full_dimensional.py
/Users/talos/.local/lib/python3.10/site-packages/dingo-0.1.0-py3.10-macosx-11.1-arm64.egg/dingo/PolytopeSampler.py:100: UserWarning: We continue without redundancy removal (slow mode is ON)
  warnings.warn(
.This model seems to have metCharge instead of metCharges field. Will use metCharge for what metCharges represents.
Restricted license - for non-production use only - expires 2024-10-28
No defined compartments in model e_coli_core. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e
/Users/talos/miniconda3/envs/dingo_p310/lib/python3.10/site-packages/optlang/gurobi_interface.py:728: DeprecationWarning: Deprecated, pass a TempConstr or use Model.addLConstr
  self.problem.addConstr(lhs, sense, rhs, name=constraint.name)
This model seems to have metCharge instead of metCharges field. Will use metCharge for what metCharges represents.
No defined compartments in model e_coli_core. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e
..
----------------------------------------------------------------------
Ran 3 tests in 0.947s

OK
```

```
(dingo_p310) talos at programming_projects/dingo % python3 tests/max_ball.py
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

```
(dingo_p310) talos at programming_projects/dingo % python3 tests/scaling.py
.This model seems to have metCharge instead of metCharges field. Will use metCharge for what metCharges represents.
Restricted license - for non-production use only - expires 2024-10-28
No defined compartments in model e_coli_core. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e
/Users/talos/miniconda3/envs/dingo_p310/lib/python3.10/site-packages/optlang/gurobi_interface.py:728: DeprecationWarning: Deprecated, pass a TempConstr or use Model.addLConstr
  self.problem.addConstr(lhs, sense, rhs, name=constraint.name)
This model seems to have metCharge instead of metCharges field. Will use metCharge for what metCharges represents.
No defined compartments in model e_coli_core. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e
..
----------------------------------------------------------------------
Ran 3 tests in 0.374s

OK
```

```
(dingo_p310) talos at programming_projects/dingo % python3 tests/rounding.py
EE
======================================================================
ERROR: test_rounding_john_position (__main__.TestSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/talos/Documents/programming_projects/dingo/tests/rounding.py", line 86, in test_rounding_john_position
    temp = np.full((samples.shape[0], samples.shape[1]), Tr_shift)
  File "/Users/talos/miniconda3/envs/dingo_p310/lib/python3.10/site-packages/numpy/core/numeric.py", line 344, in full
    multiarray.copyto(a, fill_value, casting='unsafe')
  File "<__array_function__ internals>", line 180, in copyto
ValueError: could not broadcast input array from shape (24,) into shape (24,1000)

======================================================================
ERROR: test_rounding_min_ellipsoid (__main__.TestSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/talos/Documents/programming_projects/dingo/tests/rounding.py", line 47, in test_rounding_min_ellipsoid
    temp = np.full((samples.shape[0], samples.shape[1]), Tr_shift)
  File "/Users/talos/miniconda3/envs/dingo_p310/lib/python3.10/site-packages/numpy/core/numeric.py", line 344, in full
    multiarray.copyto(a, fill_value, casting='unsafe')
  File "<__array_function__ internals>", line 180, in copyto
ValueError: could not broadcast input array from shape (24,) into shape (24,1000)

----------------------------------------------------------------------
Ran 2 tests in 1.090s

FAILED (errors=2)
```

```
(dingo_p310) talos at programming_projects/dingo % python3 tests/sampling.py
phase 1: number of correlated samples = 500, effective sample size = 3, ratio of the maximum singilar value over the minimum singular value = 2719.29
phase 2: number of correlated samples = 500, effective sample size = 6, ratio of the maximum singilar value over the minimum singular value = 171.69
phase 3: number of correlated samples = 500, effective sample size = 3, ratio of the maximum singilar value over the minimum singular value = 267.083
phase 4: number of correlated samples = 500, effective sample size = 63, ratio of the maximum singilar value over the minimum singular value = 78.4334
phase 5: number of correlated samples = 500, effective sample size = 182, ratio of the maximum singilar value over the minimum singular value = 2.9784
phase 6: number of correlated samples = 2400, effective sample size = 1012
phase 7: number of correlated samples = 2400, effective sample size = 850
phase 8: number of correlated samples = 2400, effective sample size = 833
phase 9: number of correlated samples = 2400, effective sample size = 895
phase 10: number of correlated samples = 2400, effective sample size = 965
phase 11: number of correlated samples = 2400, effective sample size = 944
phase 12: number of correlated samples = 2400, effective sample size = 1045
phase 13: number of correlated samples = 2400, effective sample size = 946
phase 14: number of correlated samples = 2400, effective sample size = 939
phase 15: number of correlated samples = 2400, effective sample size = 988
phase 16: number of correlated samples = 2400, effective sample size = 882
phase 17: number of correlated samples = 2400, effective sample size = 961
phase 18: number of correlated samples = 2400, effective sample size = 989
phase 19: number of correlated samples = 2400, effective sample size = 907
phase 20: number of correlated samples = 2400, effective sample size = 959
phase 21: number of correlated samples = 2400, effective sample size = 899
phase 22: number of correlated samples = 2400, effective sample size = 899
phase 23: number of correlated samples = 2400, effective sample size = 1013
phase 24: number of correlated samples = 2400, effective sample size = 1026
phase 25: number of correlated samples = 2400, effective sample size = 856
phase 26: number of correlated samples = 2400, effective sample size = 933
phase 27: number of correlated samples = 100, effective sample size = 20
[4]total ess 20018: number of correlated samples = 53000
[4]maximum marginal PSRF: 1.00329


.This model seems to have metCharge instead of metCharges field. Will use metCharge for what metCharges represents.
Restricted license - for non-production use only - expires 2024-10-28
No defined compartments in model e_coli_core. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e
/Users/talos/miniconda3/envs/dingo_p310/lib/python3.10/site-packages/optlang/gurobi_interface.py:728: DeprecationWarning: Deprecated, pass a TempConstr or use Model.addLConstr
  self.problem.addConstr(lhs, sense, rhs, name=constraint.name)
This model seems to have metCharge instead of metCharges field. Will use metCharge for what metCharges represents.
No defined compartments in model e_coli_core. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e
phase 1: number of correlated samples = 500, effective sample size = 7, ratio of the maximum singilar value over the minimum singular value = 2100.19
phase 2: number of correlated samples = 500, effective sample size = 17, ratio of the maximum singilar value over the minimum singular value = 224.297
phase 3: number of correlated samples = 500, effective sample size = 4, ratio of the maximum singilar value over the minimum singular value = 291.008
phase 4: number of correlated samples = 500, effective sample size = 113, ratio of the maximum singilar value over the minimum singular value = 19.7414
phase 5: number of correlated samples = 500, effective sample size = 106, ratio of the maximum singilar value over the minimum singular value = 2.37356
phase 6: number of correlated samples = 2400, effective sample size = 927
phase 7: number of correlated samples = 2400, effective sample size = 896
phase 8: number of correlated samples = 2400, effective sample size = 892
phase 9: number of correlated samples = 2400, effective sample size = 862
phase 10: number of correlated samples = 2400, effective sample size = 956
phase 11: number of correlated samples = 2400, effective sample size = 1017
phase 12: number of correlated samples = 2400, effective sample size = 1047
phase 13: number of correlated samples = 2400, effective sample size = 745
phase 14: number of correlated samples = 2400, effective sample size = 918
phase 15: number of correlated samples = 2400, effective sample size = 1007
phase 16: number of correlated samples = 2400, effective sample size = 969
phase 17: number of correlated samples = 2400, effective sample size = 932
phase 18: number of correlated samples = 2400, effective sample size = 871
phase 19: number of correlated samples = 2400, effective sample size = 912
phase 20: number of correlated samples = 2400, effective sample size = 915
phase 21: number of correlated samples = 2400, effective sample size = 960
phase 22: number of correlated samples = 2400, effective sample size = 879
phase 23: number of correlated samples = 2400, effective sample size = 868
phase 24: number of correlated samples = 2400, effective sample size = 915
phase 25: number of correlated samples = 2400, effective sample size = 910
phase 26: number of correlated samples = 2400, effective sample size = 896
phase 27: number of correlated samples = 1300, effective sample size = 478
[4]total ess 20019: number of correlated samples = 54200
[4]maximum marginal PSRF: 1.00022


.phase 1: number of correlated samples = 500, effective sample size = 14, ratio of the maximum singilar value over the minimum singular value = 1855.5
phase 2: number of correlated samples = 500, effective sample size = 7, ratio of the maximum singilar value over the minimum singular value = 128.7
phase 3: number of correlated samples = 500, effective sample size = 8, ratio of the maximum singilar value over the minimum singular value = 164.645
phase 4: number of correlated samples = 500, effective sample size = 41, ratio of the maximum singilar value over the minimum singular value = 90.9548
phase 5: number of correlated samples = 500, effective sample size = 137, ratio of the maximum singilar value over the minimum singular value = 2.93679
phase 6: number of correlated samples = 2400, effective sample size = 914
phase 7: number of correlated samples = 2400, effective sample size = 932
phase 8: number of correlated samples = 2400, effective sample size = 919
phase 9: number of correlated samples = 2400, effective sample size = 865
phase 10: number of correlated samples = 2400, effective sample size = 841
phase 11: number of correlated samples = 2400, effective sample size = 939
phase 12: number of correlated samples = 2400, effective sample size = 1005
phase 13: number of correlated samples = 2400, effective sample size = 904
phase 14: number of correlated samples = 2400, effective sample size = 949
phase 15: number of correlated samples = 2400, effective sample size = 898
phase 16: number of correlated samples = 2400, effective sample size = 1001
phase 17: number of correlated samples = 2400, effective sample size = 787
phase 18: number of correlated samples = 2400, effective sample size = 877
phase 19: number of correlated samples = 2400, effective sample size = 881
phase 20: number of correlated samples = 2400, effective sample size = 858
phase 21: number of correlated samples = 2400, effective sample size = 993
phase 22: number of correlated samples = 2400, effective sample size = 957
phase 23: number of correlated samples = 2400, effective sample size = 939
phase 24: number of correlated samples = 2400, effective sample size = 901
phase 25: number of correlated samples = 2400, effective sample size = 996
phase 26: number of correlated samples = 2400, effective sample size = 821
phase 27: number of correlated samples = 1600, effective sample size = 648
[4]total ess 20032: number of correlated samples = 54500
[4]maximum marginal PSRF: 1.0003


.
----------------------------------------------------------------------
Ran 3 tests in 5.724s

OK
```

```
(dingo_p310) talos at programming_projects/dingo % python3 tests/fast_implementation_test.py
phase 1: number of correlated samples = 500, effective sample size = 7, ratio of the maximum singilar value over the minimum singular value = 1189.49
phase 2: number of correlated samples = 500, effective sample size = 4, ratio of the maximum singilar value over the minimum singular value = 88.5752
phase 3: number of correlated samples = 500, effective sample size = 5, ratio of the maximum singilar value over the minimum singular value = 156.261
phase 4: number of correlated samples = 500, effective sample size = 12, ratio of the maximum singilar value over the minimum singular value = 177.529
phase 5: number of correlated samples = 500, effective sample size = 111, ratio of the maximum singilar value over the minimum singular value = 2.64429
phase 6: number of correlated samples = 2400, effective sample size = 1001
[5]total ess 1140: number of correlated samples = 4900
[5]maximum marginal PSRF: 1.002


....
----------------------------------------------------------------------
Ran 4 tests in 0.812s

OK
```

**Comment by hariszaf** [comment]
@savvas-paragkamian that's great news! 
So, the issue was only the conflict between Python 3.11 and the numpy version that dingo uses.
The unit test failure it's from our side I think. 
@vissarion maybe edit the `.toml` file so a python version from 3.8 up to 3.10 is used and close the issue ?

**Comment by vissarion** [comment]
@hariszaf is not clear to me whether python 3.8 and numpy 1.20 are incompatible. There are like this for 2 years.

@savvas-paragkamian please open a new issue with the unit test errors.

**Comment by hariszaf** [comment]
Python 11 seems to be incompatible. 
We now use any python version higher than 3.8.
